version: '3.8' #docker-compose version-limo

services:
  tomcat: 
    image: tomcat: 8.0
    ports:
      - 8080:8080

  tomcat01: 
    image: tomcat: 8.0
    ports:
      - 8081:8080
    
  redis:
    image: redis:5.012
    ports:
      - "6379:6379"
  mysql:
    image: mysql:5.6    
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"	
